### ISSUE TITLE
More information regarding compiler design

### ISSUE THREAD

**Issue by inikulin** [js-js/js.js#1]
Hi.

Interesting project, I would definetly keep my eye on it! Can you please provide more information regarding compiler and vm design. As I can see, currently it will instantly produce optimized code and doesn't have baseline compiler. Meanwhile, I can't see code for the IC stubs, so if I get it correct optimized code just bailouts in polymorphic cases and then whole function is recompiled with optimizing compiler. Is this correct? And I have a suggestion: it would be nice to have all parts (ssa, gc, etc.) of the vm in one repo, so it would be much easier to navigate the code.

**Comment by indutny** [comment]
@inikulin heya! it does not optimise anything. I'd say that it would probably cool to create an `js.js` org.

**Comment by inikulin** [comment]
Oh, I was confused by this line: https://github.com/js-js/js.js/blob/master/lib/js/compiler.js#L42 which made me think you perform SSA-enabled optimizations here, but now I see that it's not implemented yet.

**Comment by indutny** [comment]
Yeah, it is just a stub-out code right now.
