### ISSUE TITLE
WHY?

### ISSUE THREAD

**Issue by ghost** [js-js/js.js#33]
Hello! Sorry, if issues page isn't the good place for asking question ;) When I visited this repo, I had only one question: Why to create js runtime written in js that running in runtime?)

**Comment by indutny** [comment]
Experimentation, fun, learning, OS written in JS with compiler written in JS too?

**Comment by indutny** [comment]
And we do have #jit.js IRC channel, btw ;)

**Comment by Fishrock123** [comment]
#jsception

that law that says everything that can be written in javascript will be written in javascript

etc :)

**Comment by ghost** [comment]
@indutny reasonable :)
